import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

export default function Terms() {
  const navigate = useNavigate()

  return (
    <div className="min-h-dvh px-6 py-10" style={{ background: '#0D0D0F', color: '#D1D5DB' }}>
      <div className="max-w-2xl mx-auto">
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-sm mb-8 transition-opacity hover:opacity-70"
          style={{ color: '#A78BFA' }}
        >
          <ArrowLeft size={16} />
          Back
        </button>

        <h1 className="text-2xl font-bold text-white mb-1">Terms of Service</h1>
        <p className="text-xs mb-8" style={{ color: '#4B5563' }}>Last updated: March 2026</p>

        <div className="flex flex-col gap-6 text-sm leading-relaxed">

          <section>
            <h2 className="text-white font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>By accessing or using dweebs.lol ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">2. Description of Service</h2>
            <p>dweebs.lol is an AI-powered group character chat platform that allows users to create and participate in fictional character conversations. The Service uses AI models to generate character responses for entertainment purposes.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">3. Eligibility</h2>
            <p>You must be at least 13 years of age to use the Service. By using dweebs.lol, you represent that you meet this requirement. If you are under 18, you should have parental consent.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">4. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorised use of your account. We reserve the right to terminate accounts that violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">5. Acceptable Use</h2>
            <p className="mb-2">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside flex flex-col gap-1" style={{ color: '#9CA3AF' }}>
              <li>Generate content that is hateful, threatening, or harasses others</li>
              <li>Attempt to circumvent rate limits or abuse the AI functionality</li>
              <li>Impersonate real individuals in harmful ways</li>
              <li>Use the Service for any unlawful purpose</li>
              <li>Scrape, reverse-engineer, or copy the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">6. AI-Generated Content</h2>
            <p>Content generated by AI characters on dweebs.lol is fictional and for entertainment only. We do not guarantee accuracy, and the views expressed by AI characters do not reflect those of dweebs.lol or Cloud Labs. Do not rely on AI-generated content for real-world decisions.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">7. Intellectual Property</h2>
            <p>The dweebs.lol platform, logo, and original code are owned by Cloud Labs. Character names and likenesses belong to their respective owners. We claim no ownership over fictional characters used within the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">8. Limitation of Liability</h2>
            <p>dweebs.lol is provided "as is" without warranties of any kind. To the maximum extent permitted by law, Cloud Labs shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">9. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will note the last updated date at the top of this page.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold mb-2">10. Contact</h2>
            <p>For questions about these Terms, contact us via the feedback form in the app.</p>
          </section>

        </div>

        <p className="text-xs mt-10" style={{ color: '#374151' }}>© 2025 dweebs.lol · Made by Cloud Labs</p>
      </div>
    </div>
  )
}
